spring.application.name=kanban-task-manager

# MongoDB Configuration
spring.mongodb.uri=mongodb+srv://aryannagardhankar2002_db_user:Aryan8421@cluster0.va5tptz.mongodb.net/Trello?retryWrites=true&w=majority&appName=Trello
